### ISSUE TITLE
Support Scala 2.11

### ISSUE THREAD

**Issue by ExNexu** [markschaake/sprest#23]
I've just seen that there are no packages for Scala 2.11 yet so I started to play around with the build files and it seemed to be an easy integration except for the Slick dependency ( https://github.com/slick/slick/issues/839 ). After upgrading Slick to 2.1, it should be easy to support Scala 2.11 in Sprest.

**Comment by tigran10** [comment]
Hi there, I wonder if you have published builds for 2.11 at all, i could not find them in bintray repo, we are trying to make things work with 2.10 but getting problems with scala runtime. 

Thanks,
T

**Comment by markschaake** [comment]
I _think_ 0.3.9 is cross-compiled to 2.11. It has been a while and I have not been actively maintaining sprest. Here is the bintray artrifact which claims scala 2.11.2 compat: https://bintray.com/markschaake/maven/sprest-core/0.3.9/view

**Comment by dbergin** [comment]
Hey Mark I have been using Sprest for awhile with Scala 2.10.  Is there support yet for 2.11?  I tried to import it with 2.11.2 and did not have success.

**Comment by markschaake** [comment]
Hi Dennis. I just checked and looks like I never published a 2.11 version (but did cross-compile).

If all you need is a 2.11 version, I can see if I can publish the artifacts later tonight or tomorrow. However, my time is very limited at the moment and if I hit a speed bump I'll likely just stop trying. I'll let you know either way.

FYI: I am no longer maintaining sprest. If you're up for up, I'd recommend forking the project and publish your own version. I'd be happy to help you along that path if you want to take it on.

**Comment by dbergin** [comment]
Hi Mark
Thanks so much for responding.
I have upgraded our project to 2.11 for the newer Akka code.
Otherwise I would be fine staying at 2.10.  I really like using the sorest-reactivemongo library, so I prefer not to move away from it.

I would be open to trying to fork and publish the version, but I am not that proficient in dealing with all of the dependencies.  
If you could do it without utilizing much time that would be awesome.  If not, then any guidance for be appreciated for me to try.

Thanks
Dennis

Dr. Dennis L. Bergin
President
Shenandoah Research and Technology
703.855.1897
dennis.bergin@shenandoahresearch.com <mailto:dennis.bergin@shenandoahresearch.com>


Shenandoah Research and Technology
1205 River Rd
New Market, VA 22844
www.shenandoahresearch.com <http://www.shenandoahresearch.com/>

Hard Problems? Real Solutions!

**Comment by markschaake** [comment]
Hi Dennis,

I've spent a little longer on this than I wanted to... but in the end I figured it out. I've fixed the 2.11 build and published a version for 2.11. The current version is now `0.3.12`. README has been updated.

**Comment by dbergin** [comment]
Hi Mark
Thank you  much.  Sorry it took you longer.  I really do appreciate it!
Dennis
'
